
from operator import attrgetter
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType, RestrictedClassType, TypedListType
from pyangbind.lib.yangtypes import YANGBool, YANGListType, YANGDynClass, ReferenceType
from pyangbind.lib.base import PybindBase
from decimal import Decimal
from bitarray import bitarray
import __builtin__
import collections
def isEmpty(val):
    """ Check weather val is empty 
    
    Args:
    Val : Value need to check
    Returns:
    True: if the value is empty
    False: if the value is not empty
    """
    if(val == None):
        return True
    if isinstance(val, list):
        return len(val) == 0
    if isinstance(val, str):
        return val.strip() == ''
    if isinstance(val, unicode):
        return str(val).strip() == ''
       
    return False
import extcommunity_list
class extcommunity_lists(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module controller - based on the path /devices/device/extcommunity-lists. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_pybind_generated_by', '_netconf_operation_type', '_path_helper', '_yang_name', '_extmethods', '_module_name', '_namespace','__extcommunity_list',)

  _yang_name = 'extcommunity-lists'
  _module_name = 'l3features'
  _namespace = 'http://anutanetworks.com/l3features'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__extcommunity_list = YANGDynClass(base=YANGListType("extcommunity_list_name value",extcommunity_list.extcommunity_list, yang_name="extcommunity-list", module_name="l3features", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='extcommunity-list-name value'), is_container='list', yang_name="extcommunity-list", module_name="l3features", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/l3features', defining_module='l3features', yang_type='list', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'devices', u'device', u'extcommunity-lists']

  def _get_extcommunity_list(self):
    """
    Getter method for extcommunity_list, mapped from YANG variable /devices/device/extcommunity_lists/extcommunity_list (list)
    """
    return self.__extcommunity_list
      
  def _set_extcommunity_list(self, v, load=False):
    """
    Setter method for extcommunity_list, mapped from YANG variable /devices/device/extcommunity_lists/extcommunity_list (list)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_extcommunity_list is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_extcommunity_list() directly.
    """
    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=YANGListType("extcommunity_list_name value",extcommunity_list.extcommunity_list, yang_name="extcommunity-list", module_name="l3features", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='extcommunity-list-name value'), is_container='list', yang_name="extcommunity-list", module_name="l3features", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/l3features', defining_module='l3features', yang_type='list', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """extcommunity_list must be of a type compatible with list""",
          'defined-type': "list",
          'generated-type': """YANGDynClass(base=YANGListType("extcommunity_list_name value",extcommunity_list.extcommunity_list, yang_name="extcommunity-list", module_name="l3features", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='extcommunity-list-name value'), is_container='list', yang_name="extcommunity-list", module_name="l3features", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/l3features', defining_module='l3features', yang_type='list', is_config=True)""",
        })

    self.__extcommunity_list = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_extcommunity_list(self):
    self.__extcommunity_list = YANGDynClass(base=YANGListType("extcommunity_list_name value",extcommunity_list.extcommunity_list, yang_name="extcommunity-list", module_name="l3features", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='extcommunity-list-name value'), is_container='list', yang_name="extcommunity-list", module_name="l3features", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/l3features', defining_module='l3features', yang_type='list', is_config=True)

  extcommunity_list = __builtin__.property(_get_extcommunity_list, _set_extcommunity_list)


  _pyangbind_elements = collections.OrderedDict([('extcommunity_list', extcommunity_list), ])


