
from operator import attrgetter
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType, RestrictedClassType, TypedListType
from pyangbind.lib.yangtypes import YANGBool, YANGListType, YANGDynClass, ReferenceType
from pyangbind.lib.base import PybindBase
from decimal import Decimal
from bitarray import bitarray
import __builtin__
import collections
def isEmpty(val):
    """ Check weather val is empty 
    
    Args:
    Val : Value need to check
    Returns:
    True: if the value is empty
    False: if the value is not empty
    """
    if(val == None):
        return True
    if isinstance(val, list):
        return len(val) == 0
    if isinstance(val, str):
        return val.strip() == ''
    if isinstance(val, unicode):
        return str(val).strip() == ''
       
    return False
class event_pattern_map(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module controller - based on the path /network-functions/syslog-event-specs/syslog-event-spec/event-pattern-maps/event-pattern-map. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_pybind_generated_by', '_netconf_operation_type', '_path_helper', '_yang_name', '_extmethods', '_module_name', '_namespace','__map_id','__pattern','__naas_event_spec',)

  _yang_name = 'event-pattern-map'
  _module_name = 'networkfunctionssupport'
  _namespace = 'http://anutanetworks.com/controller'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__pattern = YANGDynClass(base=unicode, is_leaf=True, yang_name="pattern", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)
    self.__naas_event_spec = YANGDynClass(base=unicode, is_leaf=True, yang_name="naas-event-spec", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)
    self.__map_id = YANGDynClass(base=unicode, is_leaf=True, yang_name="map-id", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'network-functions', u'syslog-event-specs', u'syslog-event-spec', u'event-pattern-maps', u'event-pattern-map']

  def _get_map_id(self):
    """
    Getter method for map_id, mapped from YANG variable /network_functions/syslog_event_specs/syslog_event_spec/event_pattern_maps/event_pattern_map/map_id (string)

    YANG Description: string
    """
    return self.__map_id
      
  def _set_map_id(self, v, load=False):
    """
    Setter method for map_id, mapped from YANG variable /network_functions/syslog_event_specs/syslog_event_spec/event_pattern_maps/event_pattern_map/map_id (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_map_id is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_map_id() directly.

    YANG Description: string
    """
    parent = getattr(self, "_parent", None)
    if parent is not None and load is False:
      raise AttributeError("Cannot set keys directly when" +
                             " within an instantiated list")

    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="map-id", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """map_id must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="map-id", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)""",
        })

    self.__map_id = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_map_id(self):
    self.__map_id = YANGDynClass(base=unicode, is_leaf=True, yang_name="map-id", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)


  def _get_pattern(self):
    """
    Getter method for pattern, mapped from YANG variable /network_functions/syslog_event_specs/syslog_event_spec/event_pattern_maps/event_pattern_map/pattern (string)

    YANG Description: string
    """
    return self.__pattern
      
  def _set_pattern(self, v, load=False):
    """
    Setter method for pattern, mapped from YANG variable /network_functions/syslog_event_specs/syslog_event_spec/event_pattern_maps/event_pattern_map/pattern (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_pattern is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_pattern() directly.

    YANG Description: string
    """
    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="pattern", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """pattern must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="pattern", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)""",
        })

    self.__pattern = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_pattern(self):
    self.__pattern = YANGDynClass(base=unicode, is_leaf=True, yang_name="pattern", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)


  def _get_naas_event_spec(self):
    """
    Getter method for naas_event_spec, mapped from YANG variable /network_functions/syslog_event_specs/syslog_event_spec/event_pattern_maps/event_pattern_map/naas_event_spec (string)

    YANG Description: string
    """
    return self.__naas_event_spec
      
  def _set_naas_event_spec(self, v, load=False):
    """
    Setter method for naas_event_spec, mapped from YANG variable /network_functions/syslog_event_specs/syslog_event_spec/event_pattern_maps/event_pattern_map/naas_event_spec (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_naas_event_spec is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_naas_event_spec() directly.

    YANG Description: string
    """
    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="naas-event-spec", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """naas_event_spec must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="naas-event-spec", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)""",
        })

    self.__naas_event_spec = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_naas_event_spec(self):
    self.__naas_event_spec = YANGDynClass(base=unicode, is_leaf=True, yang_name="naas-event-spec", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)

  map_id = __builtin__.property(_get_map_id, _set_map_id)
  pattern = __builtin__.property(_get_pattern, _set_pattern)
  naas_event_spec = __builtin__.property(_get_naas_event_spec, _set_naas_event_spec)


  _pyangbind_elements = collections.OrderedDict([('map_id', map_id), ('pattern', pattern), ('naas_event_spec', naas_event_spec), ])


