
from operator import attrgetter
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType, RestrictedClassType, TypedListType
from pyangbind.lib.yangtypes import YANGBool, YANGListType, YANGDynClass, ReferenceType
from pyangbind.lib.base import PybindBase
from decimal import Decimal
from bitarray import bitarray
import __builtin__
import collections
def isEmpty(val):
    """ Check weather val is empty 
    
    Args:
    Val : Value need to check
    Returns:
    True: if the value is empty
    False: if the value is not empty
    """
    if(val == None):
        return True
    if isinstance(val, list):
        return len(val) == 0
    if isinstance(val, str):
        return val.strip() == ''
    if isinstance(val, unicode):
        return str(val).strip() == ''
       
    return False
class l2_neighbor(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module controller - based on the path /devices/device/l2-neighbors/l2-neighbor. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_pybind_generated_by', '_netconf_operation_type', '_path_helper', '_yang_name', '_extmethods', '_module_name', '_namespace','__destination_device','__destination_interface','__destination_hostname','__source_interface','__source',)

  _yang_name = 'l2-neighbor'
  _module_name = 'topology'
  _namespace = 'http://anutanetworks.com/topology'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__destination_hostname = YANGDynClass(base=unicode, default=unicode("-"), is_leaf=True, yang_name="destination-hostname", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='string', is_config=True)
    self.__source = YANGDynClass(base=RestrictedClassType(base_type=unicode,                                     restriction_type="dict_key",                                     restriction_arg={u'LLDP': {}, u'CDP': {}},), is_leaf=True, yang_name="source", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='discovery-method', is_config=True)
    self.__destination_device = YANGDynClass(base=unicode, is_leaf=True, yang_name="destination-device", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)
    self.__destination_interface = YANGDynClass(base=unicode, is_leaf=True, yang_name="destination-interface", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)
    self.__source_interface = YANGDynClass(base=unicode, is_leaf=True, yang_name="source-interface", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'devices', u'device', u'l2-neighbors', u'l2-neighbor']

  def _get_destination_device(self):
    """
    Getter method for destination_device, mapped from YANG variable /devices/device/l2_neighbors/l2_neighbor/destination_device (leafref)

    YANG Description: destination-device
    """
    return self.__destination_device
      
  def _set_destination_device(self, v, load=False):
    """
    Setter method for destination_device, mapped from YANG variable /devices/device/l2_neighbors/l2_neighbor/destination_device (leafref)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_destination_device is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_destination_device() directly.

    YANG Description: destination-device
    """
    parent = getattr(self, "_parent", None)
    if parent is not None and load is False:
      raise AttributeError("Cannot set keys directly when" +
                             " within an instantiated list")

    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="destination-device", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """destination_device must be of a type compatible with leafref""",
          'defined-type': "leafref",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="destination-device", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)""",
        })

    self.__destination_device = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_destination_device(self):
    self.__destination_device = YANGDynClass(base=unicode, is_leaf=True, yang_name="destination-device", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)


  def _get_destination_interface(self):
    """
    Getter method for destination_interface, mapped from YANG variable /devices/device/l2_neighbors/l2_neighbor/destination_interface (leafref)

    YANG Description: destination-interface
    """
    return self.__destination_interface
      
  def _set_destination_interface(self, v, load=False):
    """
    Setter method for destination_interface, mapped from YANG variable /devices/device/l2_neighbors/l2_neighbor/destination_interface (leafref)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_destination_interface is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_destination_interface() directly.

    YANG Description: destination-interface
    """
    parent = getattr(self, "_parent", None)
    if parent is not None and load is False:
      raise AttributeError("Cannot set keys directly when" +
                             " within an instantiated list")

    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="destination-interface", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """destination_interface must be of a type compatible with leafref""",
          'defined-type': "leafref",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="destination-interface", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)""",
        })

    self.__destination_interface = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_destination_interface(self):
    self.__destination_interface = YANGDynClass(base=unicode, is_leaf=True, yang_name="destination-interface", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)


  def _get_destination_hostname(self):
    """
    Getter method for destination_hostname, mapped from YANG variable /devices/device/l2_neighbors/l2_neighbor/destination_hostname (string)

    YANG Description: Destination device hostname
    """
    return self.__destination_hostname
      
  def _set_destination_hostname(self, v, load=False):
    """
    Setter method for destination_hostname, mapped from YANG variable /devices/device/l2_neighbors/l2_neighbor/destination_hostname (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_destination_hostname is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_destination_hostname() directly.

    YANG Description: Destination device hostname
    """
    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=unicode, default=unicode("-"), is_leaf=True, yang_name="destination-hostname", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='string', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """destination_hostname must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=unicode, default=unicode("-"), is_leaf=True, yang_name="destination-hostname", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='string', is_config=True)""",
        })

    self.__destination_hostname = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_destination_hostname(self):
    self.__destination_hostname = YANGDynClass(base=unicode, default=unicode("-"), is_leaf=True, yang_name="destination-hostname", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='string', is_config=True)


  def _get_source_interface(self):
    """
    Getter method for source_interface, mapped from YANG variable /devices/device/l2_neighbors/l2_neighbor/source_interface (leafref)

    YANG Description: source-interface
    """
    return self.__source_interface
      
  def _set_source_interface(self, v, load=False):
    """
    Setter method for source_interface, mapped from YANG variable /devices/device/l2_neighbors/l2_neighbor/source_interface (leafref)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_source_interface is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_source_interface() directly.

    YANG Description: source-interface
    """
    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="source-interface", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """source_interface must be of a type compatible with leafref""",
          'defined-type': "leafref",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="source-interface", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)""",
        })

    self.__source_interface = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_source_interface(self):
    self.__source_interface = YANGDynClass(base=unicode, is_leaf=True, yang_name="source-interface", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='leafref', is_config=True)


  def _get_source(self):
    """
    Getter method for source, mapped from YANG variable /devices/device/l2_neighbors/l2_neighbor/source (discovery-method)

    YANG Description: CDP
LLDP

    """
    return self.__source
      
  def _set_source(self, v, load=False):
    """
    Setter method for source, mapped from YANG variable /devices/device/l2_neighbors/l2_neighbor/source (discovery-method)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_source is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_source() directly.

    YANG Description: CDP
LLDP

    """
    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=RestrictedClassType(base_type=unicode,                                     restriction_type="dict_key",                                     restriction_arg={u'LLDP': {}, u'CDP': {}},), is_leaf=True, yang_name="source", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='discovery-method', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """source must be of a type compatible with discovery-method""",
          'defined-type': "topology:discovery-method",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=unicode,                                     restriction_type="dict_key",                                     restriction_arg={u'LLDP': {}, u'CDP': {}},), is_leaf=True, yang_name="source", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='discovery-method', is_config=True)""",
        })

    self.__source = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_source(self):
    self.__source = YANGDynClass(base=RestrictedClassType(base_type=unicode,                                     restriction_type="dict_key",                                     restriction_arg={u'LLDP': {}, u'CDP': {}},), is_leaf=True, yang_name="source", module_name="topology", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/topology', defining_module='topology', yang_type='discovery-method', is_config=True)

  destination_device = __builtin__.property(_get_destination_device, _set_destination_device)
  destination_interface = __builtin__.property(_get_destination_interface, _set_destination_interface)
  destination_hostname = __builtin__.property(_get_destination_hostname, _set_destination_hostname)
  source_interface = __builtin__.property(_get_source_interface, _set_source_interface)
  source = __builtin__.property(_get_source, _set_source)


  _pyangbind_elements = collections.OrderedDict([('destination_device', destination_device), ('destination_interface', destination_interface), ('destination_hostname', destination_hostname), ('source_interface', source_interface), ('source', source), ])


