#
# This computer program is the confidential information and proprietary trade
# secret of Anuta Networks, Inc. Possessions and use of this program must
# conform strictly to the license agreement between the user and
# Anuta Networks, Inc., and receipt or possession does not convey any rights
# to divulge, reproduce, or allow others to use this program without specific
# written authorization of Anuta Networks, Inc.
#
# Copyright (c) 2015-2016 Anuta Networks, Inc. All Rights Reserved.
#

#
#DO NOT EDIT THIS FILE ITS AUTOGENERATED ONE
#

from servicemodel import util
from servicemodel import yang
from servicemodel import devicemgr
from servicemodel.abstract_dev_mgr import AbstractDeviceMgr

def get_valid_devices(devs):
  vdevs = []
  if isinstance(devs, list):
    for dev in devs:
      drivername = dev.device.get_field_value('driver_name')
      if util.isEmpty(drivername):
        vdevs.append(dev)
  else:
    drivername = devs.device.get_field_value('driver_name')
    if util.isEmpty(drivername):
      vdevs.append(devs)

  return vdevs

class domain_lists(object):
  #XPATH devices/device/domain-lists/domain-list
  class domain_list(AbstractDeviceMgr):
    key_hints = [[]]
    def getRcpathPayload(self, sdata, dev, mapping_dict):
      dev = get_valid_devices(dev)
      if len(dev) == 0:
        return
      #convert parent keys to list
      rcpath_list = []
      payload_list = []
      ##prepare rcpath
      rcpath = "wanoptimizer:domain-lists"
      rcpath_list.append(rcpath)
      mapping_dict = kwargs.get('mapping_dict')

      #validating inputs and get payload object
      domain_list_object_list = self.validate_inputs_form_payload(mapping_dict)

      for domain_list_object in domain_list_object_list:
        #fetch payload
        domain_list_payload = domain_list_object.getxml(filter=True)
        util.log_debug('domain_list_payload %s'%domain_list_payload)
        payload_list.append(domain_list_payload)

      return rcpath_list, payload_list

    def create(self, sdata, dev, mapping_dict, addref=True, autocommit=True):
      dev = get_valid_devices(dev)
      if len(dev) == 0:
        return
      #convert parent keys to list
      ##prepare rcpath
      rcpath = "wanoptimizer:domain-lists"
      self.create_(sdata, dev, mapping_dict=mapping_dict, addref=addref, autocommit=autocommit, rcpath=rcpath)

    def create_(self, sdata, dev, **kwargs):
      mapping_dict = kwargs.get('mapping_dict')

      #validating inputs and get payload object
      domain_list_object_list = self.validate_inputs_form_payload(mapping_dict)

      for domain_list_object in domain_list_object_list:
        #fetch payload
        domain_list_payload = domain_list_object.getxml(filter=True)

        util.log_debug('domain_list_payload %s'%domain_list_payload)

        #call the base abstract class for createData
        super(self.__class__, self).create_(sdata, dev, rcpath=kwargs.get('rcpath'), payload=domain_list_payload, key_hints=self.key_hints, addref=kwargs.get('addref', True), autocommit=kwargs.get('autocommit', True), mapping_dict=mapping_dict)

    def update(self, sdata, dev, mapping_dict, addref=False, autocommit=True):
      dev = get_valid_devices(dev)
      if len(dev) == 0:
        return

      ##prepare rcpath
      rcpath = "wanoptimizer:domain-lists"
      self.update_(sdata, dev, mapping_dict=mapping_dict, addref=addref, autocommit=autocommit, rcpath=rcpath)

    def update_(self, sdata, dev, **kwargs):
      mapping_dict = kwargs.get('mapping_dict')

      #validating inputs and get payload object
      domain_list_object_list = self.validate_inputs_form_payload(mapping_dict, update=True)

      #convert keys to list
      domain_list_value = mapping_dict.get('domain_list_value')
      if not isinstance(domain_list_value, list):
        domain_list_value = [domain_list_value]

      #prepare rcpath
      rcpath = kwargs.get('rcpath')
      rcpath_list = []
      for domain_list_value_iterator in domain_list_value:
        rcpath_tmp =  rcpath+"/domain-list=%s"%(util.make_interfacename(domain_list_value_iterator))
        rcpath_list.append(rcpath_tmp)
      for rc_counter, domain_list_object in enumerate(domain_list_object_list):
        #fetch payload
        domain_list_payload = domain_list_object.getxml(filter=True)

        util.log_debug('update domain_list_payload %s'%domain_list_payload)

        rcpath = rcpath_list[rc_counter]
        #call the base abstract class for createData
        super(self.__class__, self).update_(sdata, dev, rcpath=rcpath, payload=domain_list_payload, key_hints=self.key_hints, addref=kwargs.get('addref', False), autocommit=kwargs.get('autocommit', True), mapping_dict=mapping_dict)

    def delete(self, sdata, dev, mapping_dict, fail_silently=False, remove_reference=False):
      dev = get_valid_devices(dev)
      if len(dev) == 0:
        return

      ##prepare rcpath
      rcpath = "wanoptimizer:domain-lists"
      self.delete_(sdata, dev, mapping_dict=mapping_dict, fail_silently=fail_silently, remove_reference=remove_reference, rcpath=rcpath)

    def delete_(self, sdata, dev, **kwargs):
      mapping_dict = kwargs.get('mapping_dict')

      #validating inputs
      if util.isEmpty(mapping_dict.get('domain_list_value')):
        raise Exception("'domain_list_value' cannot be empty")

      #convert keys to list
      domain_list_value = mapping_dict.get('domain_list_value')
      if not isinstance(domain_list_value, list):
        domain_list_value = [domain_list_value]

      #prepare rcpath
      rcpath = kwargs.get('rcpath')
      rcpath_list = []
      for domain_list_value_iterator in domain_list_value:
        rcpath_tmp =  rcpath+"/domain-list=%s"%(util.make_interfacename(domain_list_value_iterator))
        rcpath_list.append(rcpath_tmp)
      payload = ''

      for rcpath in rcpath_list:
        #call the base abstract class for deleteData
        super(self.__class__, self).delete_(sdata, dev, rcpath=rcpath, payload=payload, fail_silently=kwargs.get('fail_silently', False), remove_reference=kwargs.get('remove_reference', False))

    def validate_inputs_form_payload(self, mapping_dict, update=False):
      #validating inputs
      if util.isEmpty(mapping_dict.get('domain_list_value')):
        raise Exception("'domain_list_value' cannot be empty")

      #convert keys to list
      domain_list_value = mapping_dict.get('domain_list_value')
      if not isinstance(domain_list_value, list):
        domain_list_value = [domain_list_value]

      #prepare payload
      domain_list_object_list = []
      for domain_list_value_iterator in domain_list_value:
        from servicemodel.controller.devices.device import domain_lists
        domain_list_object = domain_lists.domain_list.domain_list()
        domain_list_object.domain_list_value = domain_list_value_iterator
        domain_list_object_list.append(domain_list_object)

      return domain_list_object_list

