#
# This computer program is the confidential information and proprietary trade
# secret of Anuta Networks, Inc. Possessions and use of this program must
# conform strictly to the license agreement between the user and
# Anuta Networks, Inc., and receipt or possession does not convey any rights
# to divulge, reproduce, or allow others to use this program without specific
# written authorization of Anuta Networks, Inc.
#
# Copyright (c) 2015-2016 Anuta Networks, Inc. All Rights Reserved.
#

#
#DO NOT EDIT THIS FILE ITS AUTOGENERATED ONE
#

from servicemodel import util
from servicemodel import yang
from servicemodel import devicemgr
from servicemodel.abstract_dev_mgr import AbstractDeviceMgr

def get_valid_devices(devs):
  vdevs = []
  if isinstance(devs, list):
    for dev in devs:
      drivername = dev.device.get_field_value('driver_name')
      if util.isEmpty(drivername):
        vdevs.append(dev)
  else:
    drivername = devs.device.get_field_value('driver_name')
    if util.isEmpty(drivername):
      vdevs.append(devs)

  return vdevs

#XPATH devices/device/ntp
class ntp(AbstractDeviceMgr):
  key_hints = [[]]
  def getRcpathPayload(self, sdata, dev, mapping_dict):
    dev = get_valid_devices(dev)
    if len(dev) == 0:
      return
    #convert parent keys to list
    rcpath_list = []
    payload_list = []
    ##prepare rcpath
    rcpath = ""
    rcpath_list.append(rcpath)
    mapping_dict = kwargs.get('mapping_dict')

    #validating inputs and get payload object
    ntp_object_list = self.validate_inputs_form_payload(mapping_dict)

    for ntp_object in ntp_object_list:
      #fetch payload
      ntp_payload = ntp_object.getxml(filter=True)
      util.log_debug('ntp_payload %s'%ntp_payload)
      payload_list.append(ntp_payload)

    return rcpath_list, payload_list

  def create(self, sdata, dev, mapping_dict, addref=True, autocommit=True):
    dev = get_valid_devices(dev)
    if len(dev) == 0:
      return
    #convert parent keys to list
    ##prepare rcpath
    rcpath = ""
    self.create_(sdata, dev, mapping_dict=mapping_dict, addref=addref, autocommit=autocommit, rcpath=rcpath)

  def create_(self, sdata, dev, **kwargs):
    mapping_dict = kwargs.get('mapping_dict')

    #validating inputs and get payload object
    ntp_object_list = self.validate_inputs_form_payload(mapping_dict)

    for ntp_object in ntp_object_list:
      #fetch payload
      ntp_payload = ntp_object.getxml(filter=True)

      util.log_debug('ntp_payload %s'%ntp_payload)

      #call the base abstract class for createData
      super(self.__class__, self).create_(sdata, dev, rcpath=kwargs.get('rcpath'), payload=ntp_payload, key_hints=self.key_hints, addref=kwargs.get('addref', True), autocommit=kwargs.get('autocommit', True), mapping_dict=mapping_dict)

  def update(self, sdata, dev, mapping_dict, addref=False, autocommit=True):
    dev = get_valid_devices(dev)
    if len(dev) == 0:
      return

    ##prepare rcpath
    rcpath = ""
    self.update_(sdata, dev, mapping_dict=mapping_dict, addref=addref, autocommit=autocommit, rcpath=rcpath)

  def update_(self, sdata, dev, **kwargs):
    mapping_dict = kwargs.get('mapping_dict')

    #validating inputs and get payload object
    ntp_object_list = self.validate_inputs_form_payload(mapping_dict, update=True)

    #convert keys to list

    #prepare rcpath
    rcpath = kwargs.get('rcpath')
    rcpath_list = []
    rcpath_tmp =  rcpath+"/ntp"
    rcpath_list.append(rcpath_tmp)
    for rc_counter, ntp_object in enumerate(ntp_object_list):
      #fetch payload
      ntp_payload = ntp_object.getxml(filter=True)

      util.log_debug('update ntp_payload %s'%ntp_payload)

      rcpath = rcpath_list[rc_counter]
      #call the base abstract class for createData
      super(self.__class__, self).update_(sdata, dev, rcpath=rcpath, payload=ntp_payload, key_hints=self.key_hints, addref=kwargs.get('addref', False), autocommit=kwargs.get('autocommit', True), mapping_dict=mapping_dict)

  def delete(self, sdata, dev, mapping_dict, fail_silently=False, remove_reference=False):
    dev = get_valid_devices(dev)
    if len(dev) == 0:
      return

    ##prepare rcpath
    rcpath = ""
    self.delete_(sdata, dev, mapping_dict=mapping_dict, fail_silently=fail_silently, remove_reference=remove_reference, rcpath=rcpath)

  def delete_(self, sdata, dev, **kwargs):
    mapping_dict = kwargs.get('mapping_dict')

    #validating inputs

    #convert keys to list

    #prepare rcpath
    rcpath = kwargs.get('rcpath')
    rcpath_list = []
    rcpath_tmp =  rcpath+"/ntp"
    rcpath_list.append(rcpath_tmp)
    payload = ''

    for rcpath in rcpath_list:
      #call the base abstract class for deleteData
      super(self.__class__, self).delete_(sdata, dev, rcpath=rcpath, payload=payload, fail_silently=kwargs.get('fail_silently', False), remove_reference=kwargs.get('remove_reference', False))

  def validate_inputs_form_payload(self, mapping_dict, update=False):
    #validating inputs

    #convert keys to list

    #prepare payload
    ntp_object_list = []
    from servicemodel.controller.devices import device
    ntp_object = device.ntp.ntp()
    try:
      if (update == False) or (update == True and str(mapping_dict.get('ntp', None)) != ''):
        ntp_object.ntp = mapping_dict.get('ntp', None)
      else:
        ntp_object.ntp._empty_tag = True
    except TypeError:
      pass
    try:
      if (update == False) or (update == True and str(mapping_dict.get('ntp_source_interface', None)) != ''):
        ntp_object.ntp_source_interface = mapping_dict.get('ntp_source_interface', None)
      else:
        ntp_object.ntp_source_interface._empty_tag = True
    except TypeError:
      pass
    try:
      if (update == False) or (update == True and str(mapping_dict.get('vrf', None)) != ''):
        ntp_object.vrf = mapping_dict.get('vrf', None)
      else:
        ntp_object.vrf._empty_tag = True
    except TypeError:
      pass
    try:
      if (update == False) or (update == True and str(mapping_dict.get('update_calendar', None)) != ''):
        ntp_object.update_calendar = mapping_dict.get('update_calendar', None)
      else:
        ntp_object.update_calendar._empty_tag = True
    except TypeError:
      pass
    ntp_object_list.append(ntp_object)

    return ntp_object_list

  #XPATH devices/device/ntp/ntp-server
  class ntp_server(AbstractDeviceMgr):
    key_hints = [[]]
    def getRcpathPayload(self, sdata, dev, mapping_dict):
      dev = get_valid_devices(dev)
      if len(dev) == 0:
        return
      #convert parent keys to list
      rcpath_list = []
      payload_list = []
      ##prepare rcpath
      rcpath = "basicDeviceConfigs:ntp"
      rcpath_list.append(rcpath)
      mapping_dict = kwargs.get('mapping_dict')

      #validating inputs and get payload object
      ntp_server_object_list = self.validate_inputs_form_payload(mapping_dict)

      for ntp_server_object in ntp_server_object_list:
        #fetch payload
        ntp_server_payload = ntp_server_object.getxml(filter=True)
        util.log_debug('ntp_server_payload %s'%ntp_server_payload)
        payload_list.append(ntp_server_payload)

      return rcpath_list, payload_list

    def create(self, sdata, dev, mapping_dict, addref=True, autocommit=True):
      dev = get_valid_devices(dev)
      if len(dev) == 0:
        return
      #convert parent keys to list
      ##prepare rcpath
      rcpath = "basicDeviceConfigs:ntp"
      self.create_(sdata, dev, mapping_dict=mapping_dict, addref=addref, autocommit=autocommit, rcpath=rcpath)

    def create_(self, sdata, dev, **kwargs):
      mapping_dict = kwargs.get('mapping_dict')

      #validating inputs and get payload object
      ntp_server_object_list = self.validate_inputs_form_payload(mapping_dict)

      for ntp_server_object in ntp_server_object_list:
        #fetch payload
        ntp_server_payload = ntp_server_object.getxml(filter=True)

        util.log_debug('ntp_server_payload %s'%ntp_server_payload)

        #call the base abstract class for createData
        super(self.__class__, self).create_(sdata, dev, rcpath=kwargs.get('rcpath'), payload=ntp_server_payload, key_hints=self.key_hints, addref=kwargs.get('addref', True), autocommit=kwargs.get('autocommit', True), mapping_dict=mapping_dict)

    def update(self, sdata, dev, mapping_dict, addref=False, autocommit=True):
      dev = get_valid_devices(dev)
      if len(dev) == 0:
        return

      ##prepare rcpath
      rcpath = "basicDeviceConfigs:ntp"
      self.update_(sdata, dev, mapping_dict=mapping_dict, addref=addref, autocommit=autocommit, rcpath=rcpath)

    def update_(self, sdata, dev, **kwargs):
      mapping_dict = kwargs.get('mapping_dict')

      #validating inputs and get payload object
      ntp_server_object_list = self.validate_inputs_form_payload(mapping_dict, update=True)

      #convert keys to list
      ntp_server_address = mapping_dict.get('ntp_server_address')
      if not isinstance(ntp_server_address, list):
        ntp_server_address = [ntp_server_address]

      #prepare rcpath
      rcpath = kwargs.get('rcpath')
      rcpath_list = []
      for ntp_server_address_iterator in ntp_server_address:
        rcpath_tmp =  rcpath+"/ntp-server=%s"%(util.make_interfacename(ntp_server_address_iterator))
        rcpath_list.append(rcpath_tmp)
      for rc_counter, ntp_server_object in enumerate(ntp_server_object_list):
        #fetch payload
        ntp_server_payload = ntp_server_object.getxml(filter=True)

        util.log_debug('update ntp_server_payload %s'%ntp_server_payload)

        rcpath = rcpath_list[rc_counter]
        #call the base abstract class for createData
        super(self.__class__, self).update_(sdata, dev, rcpath=rcpath, payload=ntp_server_payload, key_hints=self.key_hints, addref=kwargs.get('addref', False), autocommit=kwargs.get('autocommit', True), mapping_dict=mapping_dict)

    def delete(self, sdata, dev, mapping_dict, fail_silently=False, remove_reference=False):
      dev = get_valid_devices(dev)
      if len(dev) == 0:
        return

      ##prepare rcpath
      rcpath = "basicDeviceConfigs:ntp"
      self.delete_(sdata, dev, mapping_dict=mapping_dict, fail_silently=fail_silently, remove_reference=remove_reference, rcpath=rcpath)

    def delete_(self, sdata, dev, **kwargs):
      mapping_dict = kwargs.get('mapping_dict')

      #validating inputs
      if util.isEmpty(mapping_dict.get('ntp_server_address')):
        raise Exception("'ntp_server_address' cannot be empty")

      #convert keys to list
      ntp_server_address = mapping_dict.get('ntp_server_address')
      if not isinstance(ntp_server_address, list):
        ntp_server_address = [ntp_server_address]

      #prepare rcpath
      rcpath = kwargs.get('rcpath')
      rcpath_list = []
      for ntp_server_address_iterator in ntp_server_address:
        rcpath_tmp =  rcpath+"/ntp-server=%s"%(util.make_interfacename(ntp_server_address_iterator))
        rcpath_list.append(rcpath_tmp)
      payload = ''

      for rcpath in rcpath_list:
        #call the base abstract class for deleteData
        super(self.__class__, self).delete_(sdata, dev, rcpath=rcpath, payload=payload, fail_silently=kwargs.get('fail_silently', False), remove_reference=kwargs.get('remove_reference', False))

    def validate_inputs_form_payload(self, mapping_dict, update=False):
      #validating inputs
      if util.isEmpty(mapping_dict.get('ntp_server_address')):
        raise Exception("'ntp_server_address' cannot be empty")

      #convert keys to list
      ntp_server_address = mapping_dict.get('ntp_server_address')
      if not isinstance(ntp_server_address, list):
        ntp_server_address = [ntp_server_address]

      #prepare payload
      ntp_server_object_list = []
      for ntp_server_address_iterator in ntp_server_address:
        from servicemodel.controller.devices.device import ntp
        ntp_server_object = ntp.ntp_server.ntp_server()
        ntp_server_object.ntp_server_address = ntp_server_address_iterator
        try:
          if (update == False) or (update == True and str(mapping_dict.get('version', None)) != ''):
            ntp_server_object.version = mapping_dict.get('version', None)
          else:
            ntp_server_object.version._empty_tag = True
        except TypeError:
          pass
        try:
          if (update == False) or (update == True and str(mapping_dict.get('ntp_server2_address', None)) != ''):
            ntp_server_object.ntp_server2_address = mapping_dict.get('ntp_server2_address', None)
          else:
            ntp_server_object.ntp_server2_address._empty_tag = True
        except TypeError:
          pass
        try:
          if (update == False) or (update == True and str(mapping_dict.get('vrf', None)) != ''):
            ntp_server_object.vrf = mapping_dict.get('vrf', None)
          else:
            ntp_server_object.vrf._empty_tag = True
        except TypeError:
          pass
        try:
          if (update == False) or (update == True and str(mapping_dict.get('ntp_source_address', None)) != ''):
            ntp_server_object.ntp_source_address = mapping_dict.get('ntp_source_address', None)
          else:
            ntp_server_object.ntp_source_address._empty_tag = True
        except TypeError:
          pass
        try:
          if (update == False) or (update == True and str(mapping_dict.get('stratum_number', None)) != ''):
            ntp_server_object.stratum_number = mapping_dict.get('stratum_number', None)
          else:
            ntp_server_object.stratum_number._empty_tag = True
        except TypeError:
          pass
        try:
          if (update == False) or (update == True and str(mapping_dict.get('ntp_peer', None)) != ''):
            ntp_server_object.ntp_peer = mapping_dict.get('ntp_peer', None)
          else:
            ntp_server_object.ntp_peer._empty_tag = True
        except TypeError:
          pass
        try:
          if (update == False) or (update == True and str(mapping_dict.get('prefered_server', None)) != ''):
            ntp_server_object.prefered_server = mapping_dict.get('prefered_server', None)
          else:
            ntp_server_object.prefered_server._empty_tag = True
        except TypeError:
          pass
        try:
          if (update == False) or (update == True and str(mapping_dict.get('boot_server', None)) != ''):
            ntp_server_object.boot_server = mapping_dict.get('boot_server', None)
          else:
            ntp_server_object.boot_server._empty_tag = True
        except TypeError:
          pass
        try:
          if (update == False) or (update == True and str(mapping_dict.get('authkey_id', None)) != ''):
            ntp_server_object.authkey_id = mapping_dict.get('authkey_id', None)
          else:
            ntp_server_object.authkey_id._empty_tag = True
        except TypeError:
          pass
        try:
          if (update == False) or (update == True and str(mapping_dict.get('authkey_value', None)) != ''):
            ntp_server_object.authkey_value = mapping_dict.get('authkey_value', None)
          else:
            ntp_server_object.authkey_value._empty_tag = True
        except TypeError:
          pass
        ntp_server_object_list.append(ntp_server_object)

      return ntp_server_object_list

