
from operator import attrgetter
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType, RestrictedClassType, TypedListType
from pyangbind.lib.yangtypes import YANGBool, YANGListType, YANGDynClass, ReferenceType
from pyangbind.lib.base import PybindBase
from decimal import Decimal
from bitarray import bitarray
import __builtin__
import collections
def isEmpty(val):
    """ Check weather val is empty 
    
    Args:
    Val : Value need to check
    Returns:
    True: if the value is empty
    False: if the value is not empty
    """
    if(val == None):
        return True
    if isinstance(val, list):
        return len(val) == 0
    if isinstance(val, str):
        return val.strip() == ''
    if isinstance(val, unicode):
        return str(val).strip() == ''
       
    return False
class service_object(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module controller - based on the path /devices/device/object-groups/object-group/service-object. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_pybind_generated_by', '_netconf_operation_type', '_path_helper', '_yang_name', '_extmethods', '_module_name', '_namespace','__service_object_value','__service_object_type',)

  _yang_name = 'service-object'
  _module_name = 'firewall'
  _namespace = 'http://anutanetworks.com/firewall'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__service_object_value = YANGDynClass(base=unicode, is_leaf=True, yang_name="service-object-value", module_name="firewall", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/firewall', defining_module='firewall', yang_type='string', is_config=True)
    self.__service_object_type = YANGDynClass(base=RestrictedClassType(base_type=unicode,                                     restriction_type="dict_key",                                     restriction_arg={u'group': {}, u'port': {}},), is_leaf=True, yang_name="service-object-type", module_name="firewall", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/firewall', defining_module='firewall', yang_type='enumeration', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'devices', u'device', u'object-groups', u'object-group', u'service-object']

  def _get_service_object_value(self):
    """
    Getter method for service_object_value, mapped from YANG variable /devices/device/object_groups/object_group/service_object/service_object_value (string)

    YANG Description: string
    """
    return self.__service_object_value
      
  def _set_service_object_value(self, v, load=False):
    """
    Setter method for service_object_value, mapped from YANG variable /devices/device/object_groups/object_group/service_object/service_object_value (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_service_object_value is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_service_object_value() directly.

    YANG Description: string
    """
    parent = getattr(self, "_parent", None)
    if parent is not None and load is False:
      raise AttributeError("Cannot set keys directly when" +
                             " within an instantiated list")

    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="service-object-value", module_name="firewall", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/firewall', defining_module='firewall', yang_type='string', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """service_object_value must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="service-object-value", module_name="firewall", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/firewall', defining_module='firewall', yang_type='string', is_config=True)""",
        })

    self.__service_object_value = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_service_object_value(self):
    self.__service_object_value = YANGDynClass(base=unicode, is_leaf=True, yang_name="service-object-value", module_name="firewall", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/firewall', defining_module='firewall', yang_type='string', is_config=True)


  def _get_service_object_type(self):
    """
    Getter method for service_object_type, mapped from YANG variable /devices/device/object_groups/object_group/service_object/service_object_type (enumeration)

    YANG Description: port
group

    """
    return self.__service_object_type
      
  def _set_service_object_type(self, v, load=False):
    """
    Setter method for service_object_type, mapped from YANG variable /devices/device/object_groups/object_group/service_object/service_object_type (enumeration)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_service_object_type is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_service_object_type() directly.

    YANG Description: port
group

    """
    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=RestrictedClassType(base_type=unicode,                                     restriction_type="dict_key",                                     restriction_arg={u'group': {}, u'port': {}},), is_leaf=True, yang_name="service-object-type", module_name="firewall", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/firewall', defining_module='firewall', yang_type='enumeration', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """service_object_type must be of a type compatible with enumeration""",
          'defined-type': "firewall:enumeration",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=unicode,                                     restriction_type="dict_key",                                     restriction_arg={u'group': {}, u'port': {}},), is_leaf=True, yang_name="service-object-type", module_name="firewall", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/firewall', defining_module='firewall', yang_type='enumeration', is_config=True)""",
        })

    self.__service_object_type = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_service_object_type(self):
    self.__service_object_type = YANGDynClass(base=RestrictedClassType(base_type=unicode,                                     restriction_type="dict_key",                                     restriction_arg={u'group': {}, u'port': {}},), is_leaf=True, yang_name="service-object-type", module_name="firewall", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/firewall', defining_module='firewall', yang_type='enumeration', is_config=True)

  service_object_value = __builtin__.property(_get_service_object_value, _set_service_object_value)
  service_object_type = __builtin__.property(_get_service_object_type, _set_service_object_type)


  _pyangbind_elements = collections.OrderedDict([('service_object_value', service_object_value), ('service_object_type', service_object_type), ])


