
from operator import attrgetter
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType, RestrictedClassType, TypedListType
from pyangbind.lib.yangtypes import YANGBool, YANGListType, YANGDynClass, ReferenceType
from pyangbind.lib.base import PybindBase
from decimal import Decimal
from bitarray import bitarray
import __builtin__
import collections
def isEmpty(val):
    """ Check weather val is empty 
    
    Args:
    Val : Value need to check
    Returns:
    True: if the value is empty
    False: if the value is not empty
    """
    if(val == None):
        return True
    if isinstance(val, list):
        return len(val) == 0
    if isinstance(val, str):
        return val.strip() == ''
    if isinstance(val, unicode):
        return str(val).strip() == ''
       
    return False
class enumMap(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module controller - based on the path /modelmaps/enumMap. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_pybind_generated_by', '_netconf_operation_type', '_path_helper', '_yang_name', '_extmethods', '_module_name', '_namespace','__naasEnum','__modelEnum',)

  _yang_name = 'enumMap'
  _module_name = 'controller'
  _namespace = 'http://anutanetworks.com/controller'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__modelEnum = YANGDynClass(base=unicode, is_leaf=True, yang_name="modelEnum", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)
    self.__naasEnum = YANGDynClass(base=unicode, is_leaf=True, yang_name="naasEnum", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'modelmaps', u'enumMap']

  def _get_naasEnum(self):
    """
    Getter method for naasEnum, mapped from YANG variable /modelmaps/enumMap/naasEnum (string)

    YANG Description: string
    """
    return self.__naasEnum
      
  def _set_naasEnum(self, v, load=False):
    """
    Setter method for naasEnum, mapped from YANG variable /modelmaps/enumMap/naasEnum (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_naasEnum is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_naasEnum() directly.

    YANG Description: string
    """
    parent = getattr(self, "_parent", None)
    if parent is not None and load is False:
      raise AttributeError("Cannot set keys directly when" +
                             " within an instantiated list")

    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="naasEnum", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """naasEnum must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="naasEnum", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)""",
        })

    self.__naasEnum = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_naasEnum(self):
    self.__naasEnum = YANGDynClass(base=unicode, is_leaf=True, yang_name="naasEnum", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)


  def _get_modelEnum(self):
    """
    Getter method for modelEnum, mapped from YANG variable /modelmaps/enumMap/modelEnum (string)

    YANG Description: string
    """
    return self.__modelEnum
      
  def _set_modelEnum(self, v, load=False):
    """
    Setter method for modelEnum, mapped from YANG variable /modelmaps/enumMap/modelEnum (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_modelEnum is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_modelEnum() directly.

    YANG Description: string
    """
    try:
      if isEmpty(v):
        return
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="modelEnum", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """modelEnum must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="modelEnum", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)""",
        })

    self.__modelEnum = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_modelEnum(self):
    self.__modelEnum = YANGDynClass(base=unicode, is_leaf=True, yang_name="modelEnum", module_name="controller", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://anutanetworks.com/controller', defining_module='controller', yang_type='string', is_config=True)

  naasEnum = __builtin__.property(_get_naasEnum, _set_naasEnum)
  modelEnum = __builtin__.property(_get_modelEnum, _set_modelEnum)


  _pyangbind_elements = collections.OrderedDict([('naasEnum', naasEnum), ('modelEnum', modelEnum), ])


